name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    name: Run Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: .github/workflows/*.{yml,yaml}
      - uses: ./
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}