name: Usage
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    permissions: write-all
    name: Run Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: "**/*.{yml,yaml}"
      - uses: ./
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}
  run2:
    permissions: write-all
    name: Run Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./